services:
  backend:
    build: .
    container_name: expense_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - sqlite_data:/database
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data:
